# Utilisation de Debian Bullseye (version 2021)
FROM debian:11-slim

# Installation des dépendances de build du noyau
RUN apt-get update && apt-get install -y \
    build-essential \
    libncurses-dev \
    bison \
    flex \
    libssl-dev \
    libelf-dev \
    bc \
    git \
    rsync \
    kmod \
    cpio \
    && rm -rf /var/lib/apt/lists/*

# Définition du répertoire de travail
WORKDIR /usr/src/linux